name: logs
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/iLnaar/logs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extender: #^1.0.0
    git:
      url: https://github.com/iLnaar/extender.git
