name: logs
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/iLnaar/logs

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  extender: #^1.0.0
    path: c:/Users/iLnar/Documents/Projects/dart/extender

dev_dependencies:
  #pedantic: ^1.10.0
  #test: ^1.16.0
